version: "3"
services:
  # db:
  #   image: mongo:3.4
  backend:
    image: node:8.1
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm install && node app"
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 8080:8080
    command: bash -c "cd /frontend && npm install && ng build-qa && npm start"
